package Model;



import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Atabe
 */
public class MainMenu extends javax.swing.JFrame {

    
    public MainMenu(Accounts accounts) {
        initComponents();
        var img = new ImageIcon("src\\Icons/barbell.png");
        this.setIconImage(img.getImage());
        AddNewPanel.setVisible(false);
        MyProgramsPanel.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MyProgramsButton = new javax.swing.JLabel();
        ReadyProgramsButton = new javax.swing.JLabel();
        AddNewButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        AddNewPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_Reps = new javax.swing.JTextField();
        cb_MuscleGroup = new javax.swing.JComboBox<>();
        tf_Sets = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tf_Name = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        tf_ProjectName = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        New_Program = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        MyProgramsPanel = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        cb_MyPrograms = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        SelectedProgram = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        BackReps = new javax.swing.JLabel();
        ChestReps = new javax.swing.JLabel();
        ShouldersReps = new javax.swing.JLabel();
        LegReps = new javax.swing.JLabel();
        ArmReps = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Fitness Coach - Main Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        MyProgramsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-view-all-50.png"))); // NOI18N
        MyProgramsButton.setText("My program");
        MyProgramsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MyProgramsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MyProgramsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MyProgramsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProgramsButtonMouseClicked(evt);
            }
        });

        ReadyProgramsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-program-50.png"))); // NOI18N
        ReadyProgramsButton.setText("Ready Programs");
        ReadyProgramsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReadyProgramsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ReadyProgramsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReadyProgramsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReadyProgramsButtonMouseClicked(evt);
            }
        });

        AddNewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add New.png"))); // NOI18N
        AddNewButton.setText("Add New");
        AddNewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddNewButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddNewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(AddNewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MyProgramsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReadyProgramsButton)
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddNewButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MyProgramsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReadyProgramsButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        AddNewPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Kettlebell Swing", "Back", "10-20", "2-3"},
                {"Barbell Deadlift", "Back", "12", "3-4"},
                {"Barbell Bent-Over Row", "Back", "6-15", "3-4"},
                {"Pull-Up", "Back", "12+12", "3-4"},
                {"Dumbbell Single-Arm Row", "Back", "12", "3-4"},
                {"Chest-Supported Dumbbell Row", "Back", "15", "3"},
                {"Inverted Row", "Back", "12", "4"},
                {"Lat Pulldowns", "Back", "12", "3-4"},
                {"Single-Arm T-Bar Rows", "Back", "12+12", "3-4"}
            },
            new String [] {
                "Name", "Muscle Group", "Suggested Reps", "Suggested Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("Back", jScrollPane3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Incline Push Up", "Chest", "20", "1"},
                {"Flat Bench Press", "Chest", "8-12", "3"},
                {"Incline Bench Press", "Chest", "8-12", "3"},
                {"Decline Bench Press", "Chest", "8-12", "3"},
                {"Pushup", "Chest", "8-12", "3"},
                {"Cable Crossover", "Chest", "8-12", "3"},
                {"Chest Dip", "Chest", "8-12", "3"},
                {"Resistance Band Pullover", "Chest", "8-12", "3"}
            },
            new String [] {
                "Name", "Muscle Group", "Suggested Reps", "Suggested Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Chest", jScrollPane2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Overhead Press", "Shoulders", "12", "3"},
                {"Push Press", "Shoulders", "12", "3"},
                {"Barbell Shrug", "Shoulders", "12", "3"},
                {"Arnold Press", "Shoulders", "12", "3"},
                {"Leteral Raise", "Shoulders", "12", "3"},
                {"Bent-Over Reverse Raise", "Shoulders", "12", "3"}
            },
            new String [] {
                "Name", "Muscle Group", "Suggested Reps", "Suggested Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Shoulders", jScrollPane1);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Incline Bicep Curl", "Arm", "12", "3-4"},
                {"Concentration Curl", "Arm", "12+12", "3-4"},
                {"Twisting Dumbbell Curl", "Arm", "12+12", "3-4"},
                {"Underhand Seated Row", "Arm", "8-12", "3-4"},
                {"Reverse Curl Straight Bar", "Arm", "8-12", "3-4"},
                {"Leant-Forward EZ Bar Curl", "Arm", "10-12", "3-4"},
                {"Reverse-Grip EZ Bar Curl", "Arm", "8-12", "3-4"},
                {"Prone Dumbbell Spider Curl", "Arm", "12", "3-4"},
                {"One Arm Tricep Extention(Seated)", "Arm", "8-12", "3-4"}
            },
            new String [] {
                "Name", "Muscle Group", "Suggested Reps", "Suggested Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jTabbedPane1.addTab("Arm", jScrollPane5);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Back Squat", "Leg", "12-15", "3-4"},
                {"Front Squat", "Leg", "12-15", "3-4"},
                {"Romanian Deadlift", "Leg", "10-16", "3-4"},
                {"Walking Lunges", "Leg", "10-12", "2-3"},
                {"Reverse Lunge", "Leg", "10-12", "2-3"},
                {"Lateral Lunge", "Leg", "10-12", "2-3"},
                {"Stepup", "Leg", "12-25", "3-4"},
                {"Leg Press", "Leg", "12-15", "3-4"},
                {"Leg Curl", "Leg", "15", "3-4"},
                {"Calf Raises", "Leg", "10-15", "3-4"},
                {"Ham Curl", "Leg", "8-12", "3-4"}
            },
            new String [] {
                "Name", "Muscle Group", "Suggested Reps", "Suggested Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jTabbedPane1.addTab("Leg", jScrollPane4);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Name:");

        jLabel2.setText("Muscle Group:");

        jLabel3.setText("Reps:");

        jLabel4.setText("Sets:");

        tf_Reps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_RepsKeyTyped(evt);
            }
        });

        cb_MuscleGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Back", "Chest", "Shoulders", "Leg", "Arm", " " }));
        cb_MuscleGroup.setEnabled(false);

        tf_Sets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_SetsKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Import");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tf_Name.setEnabled(false);

        SaveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jLabel42.setText("Project Name:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(tf_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_Reps)
                            .addComponent(cb_MuscleGroup, javax.swing.GroupLayout.Alignment.TRAILING, 0, 170, Short.MAX_VALUE)
                            .addComponent(tf_Name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_Sets, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tf_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_MuscleGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_Reps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Sets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(tf_ProjectName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveButton)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        New_Program.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Muscle Group", "Reps", "Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(New_Program);

        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(204, 0, 0));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(204, 0, 0));
        ClearButton.setText("Clear Table");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddNewPanelLayout = new javax.swing.GroupLayout(AddNewPanel);
        AddNewPanel.setLayout(AddNewPanelLayout);
        AddNewPanelLayout.setHorizontalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddNewPanelLayout.createSequentialGroup()
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AddNewPanelLayout.setVerticalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewPanelLayout.createSequentialGroup()
                .addGroup(AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddNewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(AddNewPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(5, 5, 5))
        );

        MyProgramsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Select your programs:");

        cb_MyPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_MyProgramsActionPerformed(evt);
            }
        });

        SelectedProgram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Muscle Group", "Reps", "Sets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(SelectedProgram);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Muscle Activation");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Total number of Back reps:");

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Total number of Chest reps:");

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Total number of Shoulders reps:");

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Total number of Leg reps:");

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Total number of Arm reps:");

        BackReps.setText("0");
        BackReps.setName("BackReps"); // NOI18N

        ChestReps.setText("0");

        ShouldersReps.setText("0");

        LegReps.setText("0");

        ArmReps.setText("0");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-trash-50.png"))); // NOI18N
        jButton3.setText("Delete Program");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MyProgramsPanelLayout = new javax.swing.GroupLayout(MyProgramsPanel);
        MyProgramsPanel.setLayout(MyProgramsPanelLayout);
        MyProgramsPanelLayout.setHorizontalGroup(
            MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProgramsPanelLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArmReps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MyProgramsPanelLayout.createSequentialGroup()
                        .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_MyPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackReps)
                            .addComponent(ChestReps)
                            .addComponent(ShouldersReps)
                            .addComponent(LegReps))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(73, 73, 73)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
                .addContainerGap())
        );
        MyProgramsPanelLayout.setVerticalGroup(
            MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProgramsPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(cb_MyPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(BackReps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(ChestReps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(ShouldersReps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(LegReps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(ArmReps))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(MyProgramsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddNewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MyProgramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddNewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MyProgramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-sign-out-20.png"))); // NOI18N
        jMenuItem1.setText("Sign out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Accounts acn = Accounts.ActiveAccount();
        acn.setActive(false);
        LoginScreen lgn = new LoginScreen();
        lgn.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AddNewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewButtonMouseClicked
        AddNewPanel.setVisible(true);
        MyProgramsPanel.setVisible(false);
    }//GEN-LAST:event_AddNewButtonMouseClicked

    private void MyProgramsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProgramsButtonMouseClicked
        DefaultTableModel model = (DefaultTableModel)SelectedProgram.getModel();
        
        while(SelectedProgram.getRowCount() != 0){
            model.removeRow(0);
        }
        cb_MyPrograms.removeAllItems();
        
        AddNewPanel.setVisible(false);
        MyProgramsPanel.setVisible(true);
        RegisteredPrograms registeredPrograms = new RegisteredPrograms();
        
        
        for(String item : RegisteredPrograms.ProgramsName){
            cb_MyPrograms.addItem(item);
        }
        
        if(cb_MyPrograms.getSelectedIndex() != -1){
            BackReps.setText("0");
            ChestReps.setText("0");
            ShouldersReps.setText("0");
            LegReps.setText("0");
            ArmReps.setText("0");
            cb_MyPrograms.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_MyProgramsButtonMouseClicked

    private void ReadyProgramsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReadyProgramsButtonMouseClicked
        Desktop d = Desktop.getDesktop();
        String URL = "https://www.muscleandfitness.com/";
        try {
            d.browse(new URI(URL));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ReadyProgramsButtonMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        
        int selected_row = jTable3.getSelectedRow();
        tf_Name.setText(model.getValueAt(selected_row, 0).toString());
        cb_MuscleGroup.setSelectedItem(model.getValueAt(selected_row, 1).toString());
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        int selected_row = jTable2.getSelectedRow();
        tf_Name.setText(model.getValueAt(selected_row, 0).toString());
        cb_MuscleGroup.setSelectedItem(model.getValueAt(selected_row, 1).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int selected_row = jTable1.getSelectedRow();
        tf_Name.setText(model.getValueAt(selected_row, 0).toString());
        cb_MuscleGroup.setSelectedItem(model.getValueAt(selected_row, 1).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        
        int selected_row = jTable4.getSelectedRow();
        tf_Name.setText(model.getValueAt(selected_row, 0).toString());
        cb_MuscleGroup.setSelectedItem(model.getValueAt(selected_row, 1).toString());
        
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        
        int selected_row = jTable5.getSelectedRow();
        tf_Name.setText(model.getValueAt(selected_row, 0).toString());
        cb_MuscleGroup.setSelectedItem(model.getValueAt(selected_row, 1).toString());
        
    }//GEN-LAST:event_jTable5MouseClicked

    private void tf_RepsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_RepsKeyTyped
        if(!((Character.isDigit(evt.getKeyChar())) || (evt.getKeyChar()== KeyEvent.VK_DELETE) || (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE))){
            evt.consume();
        }
    }//GEN-LAST:event_tf_RepsKeyTyped

    private void tf_SetsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_SetsKeyTyped
        if(!((Character.isDigit(evt.getKeyChar())) || (evt.getKeyChar()== KeyEvent.VK_DELETE) || (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE))){
            evt.consume();
        }
    }//GEN-LAST:event_tf_SetsKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)New_Program.getModel();
        
        
        if((tf_Sets.getText().equals("0"))||(tf_Reps.getText().equals("") || tf_Sets.getText().equals(""))||(tf_Reps.getText().equals("0"))){
            JOptionPane.showMessageDialog(this, "Reps and sets have invalid values");
            return;
        }
        Object[] add = {tf_Name.getText(), cb_MuscleGroup.getSelectedItem(), tf_Reps.getText(), tf_Sets.getText()};
        model.addRow(add);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        Accounts acn = Accounts.ActiveAccount();
        String ProjectName = tf_ProjectName.getText();
        DefaultTableModel model = (DefaultTableModel)New_Program.getModel();
        if (ProjectName.equals("")){
            JOptionPane.showMessageDialog(this, "Project name field cannot be empty.");
            return;
        }
        if (model.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "There is no movement in the table.");
            return;
        }
        for(int i = 0; i < ProjectName.length(); i++){
            if('/' == ProjectName.charAt(i)||',' == ProjectName.charAt(i)){
                JOptionPane.showMessageDialog(this, "The project name cannot contain , or /.");
                return;
            } 
        }
        try(Scanner scn = new Scanner(new BufferedReader(new FileReader("Programs.txt")))){
            while(scn.hasNextLine()){
                String s = scn.nextLine();
                String[] Array = s.split(",");
                if(Array[1].equals(ProjectName)&&Array[0].equals(acn.getUsername())){
                    JOptionPane.showMessageDialog(this, "You have a program with this name.");
                    return;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try(BufferedWriter writer = new BufferedWriter(new FileWriter("Programs.txt",true))){
            writer.write(acn.getUsername()+","+ProjectName + "," + "0" + "," + "0" + "/");
            for (int i = 0; i < New_Program.getRowCount(); i++){
                for(int j = 0; j < New_Program.getColumnCount(); j++){
                    if(j != New_Program.getColumnCount()-1){
                        writer.write((String)model.getValueAt(i, j)+",");
                    }
                    else{
                        writer.write((String)model.getValueAt(i, j));
                    }
                }
                if(i != New_Program.getRowCount()-1){
                    writer.write("/");
                }
                else{
                    writer.write("\n");
                }
                
            }
            
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Program saved successfully.");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)New_Program.getModel();
        if(New_Program.getSelectedRow() != -1 || New_Program.getRowCount() != 0){
            model.removeRow(New_Program.getSelectedRow());
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)New_Program.getModel();
        while(New_Program.getRowCount() != 0){
            model.removeRow(0);
        }
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void cb_MyProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_MyProgramsActionPerformed
        DefaultTableModel model = (DefaultTableModel) SelectedProgram.getModel();
        Accounts acn = Accounts.ActiveAccount();
        while(SelectedProgram.getRowCount() != 0){
            model.removeRow(0);
        }
        for ( String program : RegisteredPrograms.Programs ){
            String[] find = program.split(",");
            if(find[1].equals(cb_MyPrograms.getSelectedItem())){
                MuscleActivation.reset();
                String[] Array1 = program.split("/");
                for ( int i = 1; i < Array1.length; i++ ){
                    String[] add = Array1[i].split(",");
                    model.addRow(add);
                    switch ( add[1]){
                        case "Back" -> { acn.setBackReps(Integer.valueOf(add[2])*Integer.valueOf(add[3]));
                        }
                        case "Chest" -> {acn.setChestReps(Integer.valueOf(add[2])*Integer.valueOf(add[3]));
                        }
                        case "Shoulders" -> {acn.setShouldersReps(Integer.valueOf(add[2])*Integer.valueOf(add[3]));
                        }
                        case "Leg" -> {acn.setLegReps(Integer.valueOf(add[2])*Integer.valueOf(add[3]));
                        }
                        case "Arm" -> {acn.setArmReps(Integer.valueOf(add[2])*Integer.valueOf(add[3]));
                        }
                        
                    }
                    
                }
                BackReps.setText(String.valueOf(acn.getBackReps()));
                ChestReps.setText(String.valueOf(acn.getChestReps()));
                ShouldersReps.setText(String.valueOf(acn.getShouldersReps()));
                LegReps.setText(String.valueOf(acn.getLegReps()));
                ArmReps.setText(String.valueOf(acn.getArmReps()));
                    
            }
        }
        
    }//GEN-LAST:event_cb_MyProgramsActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(JOptionPane.showConfirmDialog(this, "Do you confirm that the program will be deleted?","Remove",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            try(Scanner scn = new Scanner(new BufferedReader(new FileReader("Programs.txt")))){
                
                int deleteLine_number = 0;
                while ( scn.hasNextLine() ){
                    deleteLine_number++;
                    String ProgramInfo = scn.nextLine();
                    String[] Array = ProgramInfo.split(",");
                    if(Array[1].equals(cb_MyPrograms.getSelectedItem())){
                        cb_MyPrograms.removeItem(cb_MyPrograms.getSelectedItem());
                        cb_MyPrograms.setSelectedIndex(-1);
                        RegisteredPrograms.deleteLine(deleteLine_number);
                        RegisteredPrograms.Programs.remove(deleteLine_number-1);
                        RegisteredPrograms.ProgramsName.remove(deleteLine_number-1);
                        break;
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            BackReps.setText("0");
            ChestReps.setText("0");
            ShouldersReps.setText("0");
            LegReps.setText("0");
            ArmReps.setText("0");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(() -> {
            new MainMenu(acn).setVisible(true);
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewButton;
    private javax.swing.JPanel AddNewPanel;
    private javax.swing.JLabel ArmReps;
    private javax.swing.JLabel BackReps;
    private javax.swing.JLabel ChestReps;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel LegReps;
    private javax.swing.JLabel MyProgramsButton;
    private javax.swing.JPanel MyProgramsPanel;
    private javax.swing.JTable New_Program;
    private javax.swing.JLabel ReadyProgramsButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable SelectedProgram;
    private javax.swing.JLabel ShouldersReps;
    private javax.swing.JComboBox<String> cb_MuscleGroup;
    private javax.swing.JComboBox<String> cb_MyPrograms;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField tf_Name;
    private javax.swing.JTextField tf_ProjectName;
    private javax.swing.JTextField tf_Reps;
    private javax.swing.JTextField tf_Sets;
    // End of variables declaration//GEN-END:variables
}
